name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Report Test Results
      - name: Report Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          path: Tests/uts.json
