---
name: Generate Test Report
# This workflow is triggered manually and generates a test report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: willll/saturn-docker:gcc_14.2.0_vanilla

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          cd ${{ github.workspace }}/Tests
          make all
          zip -r BuildDrop.zip BuildDrop/
      - name: Upload executable
        if: ${{ false }}
        uses: actions/upload-artifact@v4
        with:
          name: BuildDrop.zip
          path: Tests/BuildDrop.zip
      - name: Install Mednafen
        run: |
          cd ${{ github.workspace }} 
          apt-get install -y unzip libsdl2-2.0-0 libflac-dev
          mkdir app
          cd app
          curl -L -o Mednafen.Linux.zip https://github.com/willll/mednafenSSDev/releases/download/initial/Mednafen.Linux.zip
          unzip Mednafen.Linux.zip
          

  generate-test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Report Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './Tests/*.json'
          summary-report: true
          failed-folded-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
