---
name: Generate Test Report
# This workflow is triggered manually and generates a test report
on:
  push:
    branches:
      - mainW
  pull_request:
    branches:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Report Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './Tests/*.json'
          summary-report: true
          failed-report: true
          flaky-report: true
          insights-report: true
          test-report: true
          # Order reports with the most important information first
          report-order: 'summary-report,failed-report,flaky-report,insights-report,test-report'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
